package com.stellarcrm.ai.enums;

public enum AnalysisType {
    SALES_PREDICTION,
    CUSTOMER_RISK_ASSESSMENT,
    ADVANCED_RISK_ASSESSMENT,
    BEHAVIORAL_ANALYSIS,
    DETAILED_SUCCESS_ANALYSIS,
    CUSTOMER_SEGMENTATION,
    CHURN_PREDICTION,
    CROSS_SELLING_OPPORTUNITIES
}